# mlFlow Registry QA & Prod pipeline 

trigger:
- main


pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'
    

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

- script: |
    pip install -U databricks-cli
    displayName: 'Installing databricks CLI'


- script: git checkout master
    pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12854/merge 
    displayName: 'Get Latest Branch'


- script: Run mlflow
    mlflow run https://github.com/jjaiwant328/jai-mlflow-job-test2  -b databricks --backend-config cluster-spec.json -P script_name=train.py -P model_name=sklearn --experiment-id 4480679818023526
    displayName: 'Run MLflow job'
 

